version: '3'
services:
  next-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ../:/app
    command: sh -c "npm run dev"
