import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from "react";
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

type FormData = {
  content: string
  description: string
}

export default function Home() {

  function sendToSlack() {
    // TODO: 環境変数がstring | undefined型になるのをどうにかする
    const webhookURL: string | undefined = process.env.NEXT_PUBLIC_SLACK_WORKFLOW_URL;
    const dataString = JSON.stringify({ content: formData.content, description: formData.description });
    return axios
      .post(webhookURL || 'dummy', dataString)
      .then((res) => {
        console.log(res.status);
        const response = {
          httpStatus: 201,
          message: 'success',
          body: res.statusText,
        };
        return response;
      })
      .catch((err) => {
        console.log(err.res.message);
        throw new Error;
      });
  }

  const [formData, setFormData] = useState<FormData>({
    content: '',
    description: ''
  })

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData({ ...formData, [name]: value })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.slack_message_box}>
            <div className={styles.slack_message_image}>
              <Image
                src="/trophy.png"
                alt="Trophy Image"
                className={styles.slack_message_image_icon}
                width={80}
                height={80}
                priority
              />
            </div>
            <div className={styles.slack_message_content}>
              <b>トロフィーを獲得しました</b>
              <p>{formData.content}</p>
              <div className={styles.slack_message_description}>
                <p>{formData.description}</p>
              </div>
              
            </div>
            
          </div>
        </div>
          <div className={styles.form_area}>
            <form className={styles.form}>
              <input
                type="text"
                name="content"
                onChange={e => handleChange(e)}
                value={formData.content}
              />

              <input
                type="text"
                name="description"
                onChange={e => handleChange(e)}
                value={formData.description}
              />
              {/* TODO: divではなくbuttonを使って実装したい（ページ更新が走らないようにする） */}
              <div className={styles.button} onClick={sendToSlack}>SEND</div>

            </form>
          </div>
      </main>
    </>
  )
}
